// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SdnUIClient is the client API for SdnUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SdnUIClient interface {
	// ListNetworkSpecs returns a list of Network(s) that can be started through the UI.
	ListNetworkSpecs(ctx context.Context, in *ListNetworkSpecsRequest, opts ...grpc.CallOption) (SdnUI_ListNetworkSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type sdnUIClient struct {
	cc grpc.ClientConnInterface
}

func NewSdnUIClient(cc grpc.ClientConnInterface) SdnUIClient {
	return &sdnUIClient{cc}
}

func (c *sdnUIClient) ListNetworkSpecs(ctx context.Context, in *ListNetworkSpecsRequest, opts ...grpc.CallOption) (SdnUI_ListNetworkSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SdnUI_ServiceDesc.Streams[0], "/v1.SdnUI/ListNetworkSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &sdnUIListNetworkSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SdnUI_ListNetworkSpecsClient interface {
	Recv() (*ListNetworkSpecsResponse, error)
	grpc.ClientStream
}

type sdnUIListNetworkSpecsClient struct {
	grpc.ClientStream
}

func (x *sdnUIListNetworkSpecsClient) Recv() (*ListNetworkSpecsResponse, error) {
	m := new(ListNetworkSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sdnUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.SdnUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SdnUIServer is the server API for SdnUI service.
// All implementations must embed UnimplementedSdnUIServer
// for forward compatibility
type SdnUIServer interface {
	// ListNetworkSpecs returns a list of Network(s) that can be started through the UI.
	ListNetworkSpecs(*ListNetworkSpecsRequest, SdnUI_ListNetworkSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedSdnUIServer()
}

// UnimplementedSdnUIServer must be embedded to have forward compatible implementations.
type UnimplementedSdnUIServer struct {
}

func (UnimplementedSdnUIServer) ListNetworkSpecs(*ListNetworkSpecsRequest, SdnUI_ListNetworkSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListNetworkSpecs not implemented")
}
func (UnimplementedSdnUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedSdnUIServer) mustEmbedUnimplementedSdnUIServer() {}

// UnsafeSdnUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SdnUIServer will
// result in compilation errors.
type UnsafeSdnUIServer interface {
	mustEmbedUnimplementedSdnUIServer()
}

func RegisterSdnUIServer(s grpc.ServiceRegistrar, srv SdnUIServer) {
	s.RegisterService(&SdnUI_ServiceDesc, srv)
}

func _SdnUI_ListNetworkSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListNetworkSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SdnUIServer).ListNetworkSpecs(m, &sdnUIListNetworkSpecsServer{stream})
}

type SdnUI_ListNetworkSpecsServer interface {
	Send(*ListNetworkSpecsResponse) error
	grpc.ServerStream
}

type sdnUIListNetworkSpecsServer struct {
	grpc.ServerStream
}

func (x *sdnUIListNetworkSpecsServer) Send(m *ListNetworkSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SdnUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdnUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SdnUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdnUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SdnUI_ServiceDesc is the grpc.ServiceDesc for SdnUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SdnUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.SdnUI",
	HandlerType: (*SdnUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _SdnUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListNetworkSpecs",
			Handler:       _SdnUI_ListNetworkSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sdn-ui.proto",
}
